### ISSUE TITLE
Listing tests with empty LinuxMain.swift outputs error message (Swift 5.8)

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/swift-package-manager#5744]
### Description

Running `swift test list` outputs an error for SwiftPM packages that have an empty `LinuxMain.swift`

### Expected behavior

`swift test list` to output a list of all the tests in a package

### Actual behavior

It outputs 
```
error: malformed
```

### Steps to reproduce

1. `swift package init`
2. `touch Tests/LinuxMain.swift`
3. `swift test list`

### Swift & OS version (output of `swift --version && uname -a`)

Swift version 5.8-dev (LLVM f6b60d5b8f4b443, Swift ecccce61139bbc4)
Target: x86_64-unknown-linux-gnu
Linux af-starbook 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tomerd** [comment]
@adam-fowler is this still an issue?

**Comment by adam-fowler** [comment]
Going to close this just now as I cannot replicate it.

**Comment by adam-fowler** [comment]
Re-opening, just managed to replicate this. It looks like it might be related to packages that have been built with a previous version of Swift.

**Comment by adam-fowler** [comment]
It looks like it is related to packages that have a LinuxMain.swift

**Comment by MaxDesiatov** [comment]
Assuming we don't support `LinuxMain.swift` anymore IIRC, do we need a separate issue to track that the error message itself should be fixed?

**Comment by adam-fowler** [comment]
A 5.8 release of swift should not have breaking changes in it though. Projects that built and test fine with swift 5.7 should do so with 5.8 as well.

**Comment by MaxDesiatov** [comment]
Right, so reopening this one seems more suitable then?

**Comment by adam-fowler** [comment]
I closed this issue then within 5 minutes realised it was still an issue so reopened it and managed to narrow down what the problem was.

**Comment by MaxDesiatov** [comment]
Ah, ok. I was a bit confused since the status for me is still showing up as closed.

**Comment by adam-fowler** [comment]
> Ah, ok. I was a bit confused since the status for me is still showing up as closed.

Ha I'm an idiot, forgot to re-open it

**Comment by adam-fowler** [comment]
I've also worked out the LinuxMain.swift needs to empty for the issue to occur. See https://forums.swift.org/t/test-discovery-on-linux/26203/10 for reasons why you might have an empty LinuxMain.swift

**Comment by finagolfin** [comment]
@adam-fowler, some diagnostics for this error were just merged in trunk, #6860, try it with the next trunk snapshot build- the current Aug. 25 snapshot doesn't have that commit- and see if it helps.

**Comment by adam-fowler** [comment]
I now get 
```
error: invalid list test JSON structure, produced by /home/adamfowler/Developer/server/mqtt-nio/.build/x86_64-unknown-linux-gnu/debug/mqtt-nioPackageTests.xctest --dump-tests-json, underlying error: malformed(json: "", underlyingError: Error Domain=NSCocoaErrorDomain Code=3840 "The data is not in the correct format.")
```

**Comment by neonichu** [comment]
Thanks for the update, sounds like an empty JSON is produced?

**Comment by mapedd** [comment]
@adam-fowler any luck working around this?

**Comment by adam-fowler** [comment]
@mapedd I haven't seen this in a long time. Although I've removed LinuxMain.swift from pretty much all of my projects.

**Comment by grynspan** [comment]
Closing per Adam's latest comment; if somebody's still running into this issue, please do reopen!
